import streamlit as st
import pandas as pd
import numpy as np

from core.diagnostics import compute_measurement_diagnostics
from app.branding import render_app_header, render_app_footer


# ============================================================
# PAGE FUNCTION (required for main navigation system)
# ============================================================
def run():

    # ---------- HEADER ----------
    render_app_header("Measurement Diagnostics")

    st.title("Reliability & Validity Diagnostics")

    st.markdown(
        """
        This module computes **psychometric diagnostics** for reflective measurement models:

        - **Cronbach’s Alpha**  
        - **Composite Reliability (CR)**  
        - **Average Variance Extracted (AVE)**  
        - **Construct Correlation Matrix**  
        - **HTMT (Heterotrait–Monotrait Ratio)**  

        You may upload:
        - A dataset generated by **DataSmartPLS4.0**, or  
        - Any survey dataset where item columns follow the pattern `PE_01`, `EE_02`, etc.

        Constructs are automatically detected using the **prefix** before the underscore.
        """
    )

    # ============================================================
    # 1. UPLOAD DATA
    # ============================================================
    st.subheader("1. Upload Item-Level Dataset")

    uploaded_file = st.file_uploader(
        "Upload a CSV file with item-level data (e.g., PE_01, EE_02, BI_03).",
        type=["csv"],
    )

    if uploaded_file is None:
        st.info("Please upload a CSV file to continue.")
        render_app_footer()
        return

    # load dataset
    try:
        df = pd.read_csv(uploaded_file)
    except Exception as e:
        st.error(f"Unable to load CSV file. Error: {e}")
        render_app_footer()
        return

    st.success(f"Dataset loaded: **{df.shape[0]} rows × {df.shape[1]} columns**")

    st.markdown("### Preview (first 10 rows)")
    st.dataframe(df.head(10), use_container_width=True)

    # ============================================================
    # 2. CONSTRUCT DETECTION
    # ============================================================
    st.subheader("2. Auto-Detected Constructs")

    construct_map = {}

    for col in df.columns:
        if "_" not in col:
            continue

        prefix = col.split("_")[0].strip()

        if prefix == "":
            continue

        construct_map.setdefault(prefix, []).append(col)

    if not construct_map:
        st.error(
            "⚠ No item columns detected using the pattern `CONSTRUCT_item`. "
            "Ensure your variables follow naming like PE_01, EE_02, BI_03."
        )
        render_app_footer()
        return

    # sort items inside each construct
    for c in construct_map:
        construct_map[c] = sorted(construct_map[c])

    construct_list = sorted(construct_map.keys())

    st.markdown("### Detected constructs:")
    for cons in construct_list:
        st.markdown(f"- **{cons}** → {', '.join(construct_map[cons])}")

    st.markdown("---")

    # User selects constructs
    selected_constructs = st.multiselect(
        "Select constructs to include in diagnostics:",
        options=construct_list,
        default=construct_list,
    )

    if not selected_constructs:
        st.error("You must select at least one construct.")
        render_app_footer()
        return

    # Filter only selected constructs
    construct_map = {k: v for k, v in construct_map.items() if k in selected_constructs}

    # Extract indicator columns
    indicator_cols = [col for cols in construct_map.values() for col in cols]
    items_df = df[indicator_cols].copy()

    # ============================================================
    # 3. RUN DIAGNOSTICS
    # ============================================================
    st.subheader("3. Compute Diagnostics")

    if st.button("Compute reliability & validity metrics", type="primary"):

        with st.spinner("Computing α, CR, AVE, correlations, and HTMT..."):
            try:
                diag = compute_measurement_diagnostics(items_df, construct_map)
            except Exception as e:
                st.error(f"Diagnostics failed: {e}")
                render_app_footer()
                return

        # --------------------------------------------------------
        # METRICS TABLE
        # --------------------------------------------------------
        st.markdown("### Reliability & Convergent Validity")

        metrics_df = pd.DataFrame(
            {
                "Cronbach Alpha": diag["alpha"],
                "Composite Reliability (CR)": diag["cr"],
                "AVE": diag["ave"],
            }
        ).T

        st.dataframe(metrics_df, use_container_width=True)

        st.info(
            """
            **Guidelines (not strict rules):**  
            - Cronbach α ≥ 0.70  
            - Composite Reliability ≥ 0.70  
            - AVE ≥ 0.50  
            Interpret results in theoretical context.
            """
        )

        # --------------------------------------------------------
        # CONSTRUCT CORRELATIONS
        # --------------------------------------------------------
        st.markdown("### Construct-Level Correlation Matrix")
        st.dataframe(diag["construct_correlations"], use_container_width=True)

        # --------------------------------------------------------
        # HTMT
        # --------------------------------------------------------
        st.markdown("### HTMT Matrix")
        st.dataframe(diag["htmt"], use_container_width=True)

        st.info("HTMT < 0.85 (strict) or < 0.90 (lenient) is evidence of discriminant validity.")

    else:
        st.caption("Click the button above to compute measurement diagnostics.")

    # ---------- FOOTER ----------
    render_app_footer()
